//************************************************************************************
//**  
//**  File name:     E:\Skola\Mirkoracunari\Zadaci sa proslog casa Mikroracunari\PWM i dva potenciometra 500ms\PWM_potenciometri_ms.c
//**  Title:         
//**  Description:   
//**  
//**  Generated by:  Flowcode v5.5.2.1
//**  Date:          Sunday, March 18, 2018 17:33:02
//**  Licence:       Professional
//**  Registered to: xyz
//**  Licence key:   WUK7B9
//**  
//**  
//**  http://www.matrixmultimedia.com
//**  
//************************************************************************************


#define MX_PIC

#define MX_USES_UINT8 1
#define MX_USES_SINT16 0
#define MX_USES_CHAR 0
#define MX_USES_FLOAT 0
#define MX_USES_SINT32 0
#define MX_USES_BOOL 1
#define MX_USES_UINT16 0
#define MX_USES_UINT32 0
//Defines for microcontroller
#define P16F877
#define FC_CAL_PIC
#define MX_ADC
#define MX_ADC_TYPE_30
#define MX_ADC_BITS_10
#define MX_EE
#define MX_EE_TYPE2
#define MX_EE_SIZE 256
#define MX_SPI_1
#define MX_SPI_1_MISO_PORT portc
#define MX_SPI_1_MISO_TRIS trisc
#define MX_SPI_1_MISO_PIN 4
#define MX_SPI_1_MOSI_PORT portc
#define MX_SPI_1_MOSI_TRIS trisc
#define MX_SPI_1_MOSI_PIN 5
#define MX_SPI_1_CLK_PORT portc
#define MX_SPI_1_CLK_TRIS trisc
#define MX_SPI_1_CLK_PIN 3
#define MX_SPI_1_SS_PORT portc
#define MX_SPI_1_SS_TRIS trisc
#define MX_UART_1
#define MX_UART_1_TX_PORT portc
#define MX_UART_1_TX_TRIS trisc
#define MX_UART_1_TX_PIN 6
#define MX_UART_1_RX_PORT portc
#define MX_UART_1_RX_TRIS trisc
#define MX_UART_1_RX_PIN 7
#define MX_I2C
#define MX_MI2C
#define MX_I2C_1
#define MX_I2C_1_SDA_PORT portc
#define MX_I2C_1_SDA_TRIS trisc
#define MX_I2C_1_SDA_PIN 4
#define MX_I2C_1_SCL_PORT portc
#define MX_I2C_1_SCL_TRIS trisc
#define MX_I2C_1_SCL_PIN 3
#define MX_PWM
#define MX_PWM_CNT 2
#define MX_PWM_PSCA1
#define MX_PWM_PSCA4
#define MX_PWM_PSCA16
#define MX_PWM_1_PORT portc
#define MX_PWM_1_TRIS trisc
#define MX_PWM_1_PIN 2
#define MX_PWM_2_PORT portc
#define MX_PWM_2_TRIS trisc
#define MX_PWM_2_PIN 1

//Functions
#define MX_CLK_SPEED 10000000
#ifdef _BOOSTC
#include <system.h>
#endif
#ifdef HI_TECH_C
#include <pic.h>
#endif

//Configuration data
#ifdef _BOOSTC
#pragma DATA 0x2007, 0x3f7a
#endif
#ifdef HI_TECH_C
__CONFIG(0x3f7a);
#endif

//Internal functions
#include "C:\Program Files (x86)\Flowcode\v5\FCD\internals.c"

//Macro function declarations


//Variable declarations
#define FCV_TRUE (1)
#define FCV_FALSE (0)
MX_UINT8 FCV_NAPON;
MX_UINT8 FCV_NAPONJEDAN;




//PWM(0): //Defines:

/**** Macro Substitutions ****
a = Unique Reference
b = PWM Channel - 0=SW / 1-8=HW
c = PWM Alt Pin FCD_PWM0_Enable - 0=Standard / 1=Alt
d = PWM Period
e = PWM Prescaler 1
******************************/

//Period and Prescaler Defines
#ifndef MX_PWM_PERIOD
  #define MX_PWM_PERIOD				255
#else
  #if (MX_PWM_PERIOD != 255)
    #error "PWM period value must be the same in all PWM modules"
  #endif
#endif

#ifndef MX_PWM_PRESCALE1
  #define MX_PWM_PRESCALE1			1
#else
  #if (MX_PWM_PRESCALE1 != 1)
    #error "PWM prescale value must be the same in all PWM modules"
  #endif
#endif

//Definitions for PWM slot allocation
#ifndef	MX_PWM_REF1
				#define MX_PWM_REF1
				#define PWM_2_MX_PWM_UREF			1
				#define MX_PWM_CHANNEL_1		1
				#define MX_PWM_HWALT_1			0
#else
 #ifndef	MX_PWM_REF2
				#define MX_PWM_REF2
				#define PWM_2_MX_PWM_UREF			2
				#define MX_PWM_CHANNEL_2		1
				#define MX_PWM_HWALT_2			0
 #else
  #ifndef	MX_PWM_REF3
				#define MX_PWM_REF3
				#define PWM_2_MX_PWM_UREF			3
				#define MX_PWM_CHANNEL_3		1
				#define MX_PWM_HWALT_3			0
  #else
   #ifndef	MX_PWM_REF4
				#define MX_PWM_REF4
				#define PWM_2_MX_PWM_UREF			4
				#define MX_PWM_CHANNEL_4		1
				#define MX_PWM_HWALT_4			0
   #else
    #ifndef	MX_PWM_REF5
				#define MX_PWM_REF5
				#define PWM_2_MX_PWM_UREF			5
				#define MX_PWM_CHANNEL_5		1
				#define MX_PWM_HWALT_5			0
    #else
     #ifndef	MX_PWM_REF6
				#define MX_PWM_REF6
				#define PWM_2_MX_PWM_UREF			6
				#define MX_PWM_CHANNEL_6		1
				#define MX_PWM_HWALT_6			0
     #else
      #ifndef	MX_PWM_REF7
				#define MX_PWM_REF7
				#define PWM_2_MX_PWM_UREF			7
				#define MX_PWM_CHANNEL_7		1
				#define MX_PWM_HWALT_7			0
      #else
       #ifndef	MX_PWM_REF8
				#define MX_PWM_REF8
				#define PWM_2_MX_PWM_UREF			8
				#define MX_PWM_CHANNEL_8		1
				#define MX_PWM_HWALT_8			0
       #else
        #ifndef	MX_PWM_REF9
				#define MX_PWM_REF9
				#define PWM_2_MX_PWM_UREF			9
				#define MX_PWM_CHANNEL_9		1
				#define MX_PWM_HWALT_9			0
        #else
         #ifndef	MX_PWM_REF10
				#define MX_PWM_REF10
				#define PWM_2_MX_PWM_UREF			10
				#define MX_PWM_CHANNEL_10		1
				#define MX_PWM_HWALT_10			0
         #else
          #ifndef	MX_PWM_REF11
				#define MX_PWM_REF11
				#define PWM_2_MX_PWM_UREF			11
				#define MX_PWM_CHANNEL_11		1
				#define MX_PWM_HWALT_11			0
          #else
           #ifndef	MX_PWM_REF12
				#define MX_PWM_REF12
				#define PWM_2_MX_PWM_UREF			12
				#define MX_PWM_CHANNEL_12		1
				#define MX_PWM_HWALT_12			0
           #else
            #ifndef	MX_PWM_REF13
				#define MX_PWM_REF13
				#define PWM_2_MX_PWM_UREF			13
				#define MX_PWM_CHANNEL_13		1
				#define MX_PWM_HWALT_13			0
            #else
             #ifndef	MX_PWM_REF14
				#define MX_PWM_REF14
				#define PWM_2_MX_PWM_UREF			14
				#define MX_PWM_CHANNEL_14		1
				#define MX_PWM_HWALT_14			0
             #else
         	  #ifndef	MX_PWM_REF15
				#define MX_PWM_REF15
				#define PWM_2_MX_PWM_UREF			15
				#define MX_PWM_CHANNEL_15		1
				#define MX_PWM_HWALT_15			0
              #else
               #ifndef	MX_PWM_REF16
				#define MX_PWM_REF16
				#define PWM_2_MX_PWM_UREF			16
				#define MX_PWM_CHANNEL_16		1
				#define MX_PWM_HWALT_16			0
			   #endif
			  #endif
			 #endif
			#endif
		   #endif
		  #endif
         #endif
        #endif
       #endif
      #endif
     #endif
    #endif
   #endif
  #endif
 #endif
#endif

#define PWM_2_PWM_Enable_Channel		CAL_APPEND(FC_CAL_PWM_Enable_Channel_, PWM_2_MX_PWM_UREF)
#define PWM_2_PWM_Disable_Channel		CAL_APPEND(FC_CAL_PWM_Disable_Channel_, PWM_2_MX_PWM_UREF)
#define PWM_2_PWM_Set_Duty_8Bit		CAL_APPEND(FC_CAL_PWM_Set_Duty_8Bit_, PWM_2_MX_PWM_UREF)
#define PWM_2_PWM_Change_Period		CAL_APPEND(FC_CAL_PWM_Change_Period_, PWM_2_MX_PWM_UREF)
#define PWM_2_PWM_Set_Duty_10Bit		CAL_APPEND(FC_CAL_PWM_Set_Duty_10Bit_, PWM_2_MX_PWM_UREF)

extern void PWM_2_PWM_Enable_Channel ();
extern void PWM_2_PWM_Disable_Channel ();
extern void PWM_2_PWM_Set_Duty_8Bit (MX_UINT8 duty);
extern void PWM_2_PWM_Change_Period (MX_UINT8 period, MX_UINT16 prescaler);
extern void PWM_2_PWM_Set_Duty_10Bit (MX_UINT16 duty);




//PWM(0): //Macro function declarations

void FCD_PWM0_Enable();
void FCD_PWM0_Disable();
void FCD_PWM0_SetDutyCycle(MX_UINT8 nDuty);
void FCD_PWM0_ChangePeriod(MX_UINT8 nPeriodVal, MX_UINT8 nPrescalerVal);
void FCD_PWM0_SetDutyCycle10bit(MX_SINT16 nDuty);


//ADC(0): //Defines:

/**** Macro Substitutions ****
a = Unique Reference
b = Which ADC Channel
c = Acquisition time
d = Conversion Speed
e = VRef+ Option
f = VRef Voltage x 0.01V
******************************/

//Common Defines

#define ADC_3_MX_ADC_CHANNEL	0
#define ADC_3_MX_ADC_ACTIME	40
#define ADC_3_MX_ADC_CONVSP	3
#define ADC_3_MX_ADC_VREFOP	0
#define ADC_3_MX_ADC_VREFVOL	498

#ifndef MX_ADC_CHANNEL_0
 #define MX_ADC_CHANNEL_0			//Inform CAL ADC channel 0 is now in use.
#endif

#ifndef MX_ADC_REF					//Inform CAL ADC peripheral is now in use
 #define MX_ADC_REF
#endif

extern void FC_CAL_Enable_ADC (MX_UINT8 Channel, MX_UINT8 Conv_Speed, MX_UINT8 Vref, MX_UINT8 T_Charge);
extern MX_UINT16 FC_CAL_Sample_ADC (MX_UINT8 Sample_Mode);
extern void FC_CAL_Disable_ADC (void);




//ADC(0): //Macro function declarations

void FCD_ADC0_SampleADC();
MX_UINT8 FCD_ADC0_ReadAsByte();
MX_UINT16 FCD_ADC0_ReadAsInt();
MX_FLOAT FCD_ADC0_ReadAsVoltage();
void FCD_ADC0_ReadAsString(MX_CHAR* FCR_RETVAL, MX_UINT8 FCR_RETVAL_SIZE);
void FCD_ADC0_ADC_RAW_Configure_Channel();
MX_UINT8 FCD_ADC0_ADC_RAW_Sample_Channel_Byte();
MX_UINT16 FCD_ADC0_ADC_RAW_Sample_Channel_Int();
MX_UINT8 FCD_ADC0_ADC_RAW_Average_Channel_Byte(MX_UINT8 NumSamples, MX_UINT8 DelayUs);
MX_UINT16 FCD_ADC0_ADC_RAW_Average_Channel_Int(MX_UINT8 NumSamples, MX_UINT8 DelayUs);
void FCD_ADC0_ADC_RAW_Disable_Channel();


//PWM(1): //Defines:

/**** Macro Substitutions ****
a = Unique Reference
b = PWM Channel - 0=SW / 1-8=HW
c = PWM Alt Pin FCD_PWM1_Enable - 0=Standard / 1=Alt
d = PWM Period
e = PWM Prescaler 1
******************************/

//Period and Prescaler Defines
#ifndef MX_PWM_PERIOD
  #define MX_PWM_PERIOD				255
#else
  #if (MX_PWM_PERIOD != 255)
    #error "PWM period value must be the same in all PWM modules"
  #endif
#endif

#ifndef MX_PWM_PRESCALE1
  #define MX_PWM_PRESCALE1			1
#else
  #if (MX_PWM_PRESCALE1 != 1)
    #error "PWM prescale value must be the same in all PWM modules"
  #endif
#endif

//Definitions for PWM slot allocation
#ifndef	MX_PWM_REF1
				#define MX_PWM_REF1
				#define PWM_4_MX_PWM_UREF			1
				#define MX_PWM_CHANNEL_1		2
				#define MX_PWM_HWALT_1			0
#else
 #ifndef	MX_PWM_REF2
				#define MX_PWM_REF2
				#define PWM_4_MX_PWM_UREF			2
				#define MX_PWM_CHANNEL_2		2
				#define MX_PWM_HWALT_2			0
 #else
  #ifndef	MX_PWM_REF3
				#define MX_PWM_REF3
				#define PWM_4_MX_PWM_UREF			3
				#define MX_PWM_CHANNEL_3		2
				#define MX_PWM_HWALT_3			0
  #else
   #ifndef	MX_PWM_REF4
				#define MX_PWM_REF4
				#define PWM_4_MX_PWM_UREF			4
				#define MX_PWM_CHANNEL_4		2
				#define MX_PWM_HWALT_4			0
   #else
    #ifndef	MX_PWM_REF5
				#define MX_PWM_REF5
				#define PWM_4_MX_PWM_UREF			5
				#define MX_PWM_CHANNEL_5		2
				#define MX_PWM_HWALT_5			0
    #else
     #ifndef	MX_PWM_REF6
				#define MX_PWM_REF6
				#define PWM_4_MX_PWM_UREF			6
				#define MX_PWM_CHANNEL_6		2
				#define MX_PWM_HWALT_6			0
     #else
      #ifndef	MX_PWM_REF7
				#define MX_PWM_REF7
				#define PWM_4_MX_PWM_UREF			7
				#define MX_PWM_CHANNEL_7		2
				#define MX_PWM_HWALT_7			0
      #else
       #ifndef	MX_PWM_REF8
				#define MX_PWM_REF8
				#define PWM_4_MX_PWM_UREF			8
				#define MX_PWM_CHANNEL_8		2
				#define MX_PWM_HWALT_8			0
       #else
        #ifndef	MX_PWM_REF9
				#define MX_PWM_REF9
				#define PWM_4_MX_PWM_UREF			9
				#define MX_PWM_CHANNEL_9		2
				#define MX_PWM_HWALT_9			0
        #else
         #ifndef	MX_PWM_REF10
				#define MX_PWM_REF10
				#define PWM_4_MX_PWM_UREF			10
				#define MX_PWM_CHANNEL_10		2
				#define MX_PWM_HWALT_10			0
         #else
          #ifndef	MX_PWM_REF11
				#define MX_PWM_REF11
				#define PWM_4_MX_PWM_UREF			11
				#define MX_PWM_CHANNEL_11		2
				#define MX_PWM_HWALT_11			0
          #else
           #ifndef	MX_PWM_REF12
				#define MX_PWM_REF12
				#define PWM_4_MX_PWM_UREF			12
				#define MX_PWM_CHANNEL_12		2
				#define MX_PWM_HWALT_12			0
           #else
            #ifndef	MX_PWM_REF13
				#define MX_PWM_REF13
				#define PWM_4_MX_PWM_UREF			13
				#define MX_PWM_CHANNEL_13		2
				#define MX_PWM_HWALT_13			0
            #else
             #ifndef	MX_PWM_REF14
				#define MX_PWM_REF14
				#define PWM_4_MX_PWM_UREF			14
				#define MX_PWM_CHANNEL_14		2
				#define MX_PWM_HWALT_14			0
             #else
         	  #ifndef	MX_PWM_REF15
				#define MX_PWM_REF15
				#define PWM_4_MX_PWM_UREF			15
				#define MX_PWM_CHANNEL_15		2
				#define MX_PWM_HWALT_15			0
              #else
               #ifndef	MX_PWM_REF16
				#define MX_PWM_REF16
				#define PWM_4_MX_PWM_UREF			16
				#define MX_PWM_CHANNEL_16		2
				#define MX_PWM_HWALT_16			0
			   #endif
			  #endif
			 #endif
			#endif
		   #endif
		  #endif
         #endif
        #endif
       #endif
      #endif
     #endif
    #endif
   #endif
  #endif
 #endif
#endif

#define PWM_4_PWM_Enable_Channel		CAL_APPEND(FC_CAL_PWM_Enable_Channel_, PWM_4_MX_PWM_UREF)
#define PWM_4_PWM_Disable_Channel		CAL_APPEND(FC_CAL_PWM_Disable_Channel_, PWM_4_MX_PWM_UREF)
#define PWM_4_PWM_Set_Duty_8Bit		CAL_APPEND(FC_CAL_PWM_Set_Duty_8Bit_, PWM_4_MX_PWM_UREF)
#define PWM_4_PWM_Change_Period		CAL_APPEND(FC_CAL_PWM_Change_Period_, PWM_4_MX_PWM_UREF)
#define PWM_4_PWM_Set_Duty_10Bit		CAL_APPEND(FC_CAL_PWM_Set_Duty_10Bit_, PWM_4_MX_PWM_UREF)

extern void PWM_4_PWM_Enable_Channel ();
extern void PWM_4_PWM_Disable_Channel ();
extern void PWM_4_PWM_Set_Duty_8Bit (MX_UINT8 duty);
extern void PWM_4_PWM_Change_Period (MX_UINT8 period, MX_UINT16 prescaler);
extern void PWM_4_PWM_Set_Duty_10Bit (MX_UINT16 duty);




//PWM(1): //Macro function declarations

void FCD_PWM1_Enable();
void FCD_PWM1_Disable();
void FCD_PWM1_SetDutyCycle(MX_UINT8 nDuty);
void FCD_PWM1_ChangePeriod(MX_UINT8 nPeriodVal, MX_UINT8 nPrescalerVal);
void FCD_PWM1_SetDutyCycle10bit(MX_SINT16 nDuty);


//ADC(1): //Defines:

/**** Macro Substitutions ****
a = Unique Reference
b = Which ADC Channel
c = Acquisition time
d = Conversion Speed
e = VRef+ Option
f = VRef Voltage x 0.01V
******************************/

//Common Defines

#define ADC_5_MX_ADC_CHANNEL	1
#define ADC_5_MX_ADC_ACTIME	40
#define ADC_5_MX_ADC_CONVSP	3
#define ADC_5_MX_ADC_VREFOP	0
#define ADC_5_MX_ADC_VREFVOL	498

#ifndef MX_ADC_CHANNEL_1
 #define MX_ADC_CHANNEL_1			//Inform CAL ADC channel 1 is now in use.
#endif

#ifndef MX_ADC_REF					//Inform CAL ADC peripheral is now in use
 #define MX_ADC_REF
#endif

extern void FC_CAL_Enable_ADC (MX_UINT8 Channel, MX_UINT8 Conv_Speed, MX_UINT8 Vref, MX_UINT8 T_Charge);
extern MX_UINT16 FC_CAL_Sample_ADC (MX_UINT8 Sample_Mode);
extern void FC_CAL_Disable_ADC (void);




//ADC(1): //Macro function declarations

void FCD_ADC1_SampleADC();
MX_UINT8 FCD_ADC1_ReadAsByte();
MX_UINT16 FCD_ADC1_ReadAsInt();
MX_FLOAT FCD_ADC1_ReadAsVoltage();
void FCD_ADC1_ReadAsString(MX_CHAR* FCR_RETVAL, MX_UINT8 FCR_RETVAL_SIZE);
void FCD_ADC1_ADC_RAW_Configure_Channel();
MX_UINT8 FCD_ADC1_ADC_RAW_Sample_Channel_Byte();
MX_UINT16 FCD_ADC1_ADC_RAW_Sample_Channel_Int();
MX_UINT8 FCD_ADC1_ADC_RAW_Average_Channel_Byte(MX_UINT8 NumSamples, MX_UINT8 DelayUs);
MX_UINT16 FCD_ADC1_ADC_RAW_Average_Channel_Int(MX_UINT8 NumSamples, MX_UINT8 DelayUs);
void FCD_ADC1_ADC_RAW_Disable_Channel();



//PWM(0): //Macro implementations


void FCD_PWM0_Enable()
{
	
		PWM_2_PWM_Change_Period (MX_PWM_PERIOD, MX_PWM_PRESCALE1);
		PWM_2_PWM_Enable_Channel ();

}

void FCD_PWM0_Disable()
{
	
		PWM_2_PWM_Disable_Channel();

}

void FCD_PWM0_SetDutyCycle(MX_UINT8 nDuty)
{
	
		PWM_2_PWM_Set_Duty_8Bit(nDuty);

}

void FCD_PWM0_ChangePeriod(MX_UINT8 nPeriodVal, MX_UINT8 nPrescalerVal)
{
	
		PWM_2_PWM_Change_Period (nPeriodVal, nPrescalerVal);

}

void FCD_PWM0_SetDutyCycle10bit(MX_SINT16 nDuty)
{
	
		PWM_2_PWM_Set_Duty_10Bit(nDuty);

}



//ADC(0): //Macro implementations


void FCD_ADC0_SampleADC()
{
	
	    //unused

}

MX_UINT8 FCD_ADC0_ReadAsByte()
{
	
		MX_UINT8 retVal;

		//Configure & Enable ADC Channel
		FC_CAL_Enable_ADC ( ADC_3_MX_ADC_CHANNEL , ADC_3_MX_ADC_CONVSP , ADC_3_MX_ADC_VREFOP , ADC_3_MX_ADC_ACTIME );

		retVal = FC_CAL_Sample_ADC( 0 );				//Perform Sample - Return as byte

		FC_CAL_Disable_ADC ();

		return (retVal);

}

MX_UINT16 FCD_ADC0_ReadAsInt()
{
	
		MX_UINT16 retVal;

		//Configure & Enable ADC Channel
		FC_CAL_Enable_ADC ( ADC_3_MX_ADC_CHANNEL , ADC_3_MX_ADC_CONVSP , ADC_3_MX_ADC_VREFOP , ADC_3_MX_ADC_ACTIME );

		retVal = FC_CAL_Sample_ADC( 1 );				//Perform Sample - Return as MX_UINT16

		FC_CAL_Disable_ADC ();

		return (retVal);

}

MX_FLOAT FCD_ADC0_ReadAsVoltage()
{
	
		MX_UINT16 iSample;
		MX_FLOAT fSample, fVoltage, fVperDiv;

		//Configure & Enable ADC Channel
		FC_CAL_Enable_ADC ( ADC_3_MX_ADC_CHANNEL , ADC_3_MX_ADC_CONVSP , ADC_3_MX_ADC_VREFOP , ADC_3_MX_ADC_ACTIME );

	  #ifdef MX_ADC_BITS_8
		iSample = FC_CAL_Sample_ADC( 0 );								//Perform Sample - Return as byte
	  #else
		iSample = FC_CAL_Sample_ADC( 1 );								//Perform Sample - Return as MX_UINT16
	  #endif

	  	FC_CAL_Disable_ADC ();											//Switch off ADC peripheral
		fVoltage = flt_fromi( ADC_3_MX_ADC_VREFVOL );						//Convert reference voltage count to floating point (0 - 500 x 10mV)
		fVoltage = flt_mul(fVoltage, 0.01);								//Convert reference voltage count to actual voltage (0 - 5)

	  #ifdef MX_ADC_BITS_8
		fVperDiv = flt_mul(fVoltage, 0.00390625);						//Convert actual voltage to voltage per division (VRef / 256)
	  #endif
	  #ifdef MX_ADC_BITS_10
		fVperDiv = flt_mul(fVoltage, 0.000976);							//Convert actual voltage to voltage per division (VRef / 1024)
	  #endif
	  #ifdef MX_ADC_BITS_12
		fVperDiv = flt_mul(fVoltage, 0.00024414);						//Convert actual voltage to voltage per division (VRef / 4096)
	  #endif

		fSample = flt_fromi(iSample);									//Convert to floating point variable
		fVoltage = flt_mul(fSample, fVperDiv);							//Calculate floating point voltage

		return (fVoltage);

}

void FCD_ADC0_ReadAsString(MX_CHAR* FCR_RETVAL, MX_UINT8 FCR_RETVAL_SIZE)
{
	
		MX_FLOAT fVoltage;

		fVoltage = FCD_ADC0_ReadAsVoltage();
		FCI_FLOAT_TO_STRING(fVoltage, 2, FCR_RETVAL, FCR_RETVAL_SIZE);	//Convert to String

}

void FCD_ADC0_ADC_RAW_Configure_Channel()
{
	
		//Configure & Enable ADC Channel
		FC_CAL_Enable_ADC ( ADC_3_MX_ADC_CHANNEL , ADC_3_MX_ADC_CONVSP , ADC_3_MX_ADC_VREFOP , ADC_3_MX_ADC_ACTIME );

}

MX_UINT8 FCD_ADC0_ADC_RAW_Sample_Channel_Byte()
{
	
		return FC_CAL_Sample_ADC( 0 );									//Perform Sample - Return as byte

}

MX_UINT16 FCD_ADC0_ADC_RAW_Sample_Channel_Int()
{
	
		return FC_CAL_Sample_ADC( 1 );									//Perform Sample - Return as MX_UINT16

}

MX_UINT8 FCD_ADC0_ADC_RAW_Average_Channel_Byte(MX_UINT8 NumSamples, MX_UINT8 DelayUs)
{
	
		MX_UINT32 average = 0;
		MX_UINT8 count;

		for (count=0; count<NumSamples; count++)
		{
			average = average + FC_CAL_Sample_ADC( 0 );					//Perform Sample - Return as byte - add to average

			if (DelayUs)
				delay_us(DelayUs);										//If delay is not 0 then pause between samples
		}
		average = average / count;

		return (average & 0xFF);										//Return average as byte

}

MX_UINT16 FCD_ADC0_ADC_RAW_Average_Channel_Int(MX_UINT8 NumSamples, MX_UINT8 DelayUs)
{
	
		MX_UINT32 average = 0;
		MX_UINT8 count;

		for (count=0; count<NumSamples; count++)
		{
			average = average + FC_CAL_Sample_ADC( 1 );					//Perform Sample - Return as MX_UINT16 - add to average

			if (DelayUs)
				delay_us(DelayUs);										//If delay is not 0 then pause between samples
		}
		average = average / count;

		return (average & 0x1FFF);										//Return average as MX_SINT16

}

void FCD_ADC0_ADC_RAW_Disable_Channel()
{
	
		FC_CAL_Disable_ADC ();											//Disable ADC Channel

}



//PWM(1): //Macro implementations


void FCD_PWM1_Enable()
{
	
		PWM_4_PWM_Change_Period (MX_PWM_PERIOD, MX_PWM_PRESCALE1);
		PWM_4_PWM_Enable_Channel ();

}

void FCD_PWM1_Disable()
{
	
		PWM_4_PWM_Disable_Channel();

}

void FCD_PWM1_SetDutyCycle(MX_UINT8 nDuty)
{
	
		PWM_4_PWM_Set_Duty_8Bit(nDuty);

}

void FCD_PWM1_ChangePeriod(MX_UINT8 nPeriodVal, MX_UINT8 nPrescalerVal)
{
	
		PWM_4_PWM_Change_Period (nPeriodVal, nPrescalerVal);

}

void FCD_PWM1_SetDutyCycle10bit(MX_SINT16 nDuty)
{
	
		PWM_4_PWM_Set_Duty_10Bit(nDuty);

}



//ADC(1): //Macro implementations


void FCD_ADC1_SampleADC()
{
	
	    //unused

}

MX_UINT8 FCD_ADC1_ReadAsByte()
{
	
		MX_UINT8 retVal;

		//Configure & Enable ADC Channel
		FC_CAL_Enable_ADC ( ADC_5_MX_ADC_CHANNEL , ADC_5_MX_ADC_CONVSP , ADC_5_MX_ADC_VREFOP , ADC_5_MX_ADC_ACTIME );

		retVal = FC_CAL_Sample_ADC( 0 );				//Perform Sample - Return as byte

		FC_CAL_Disable_ADC ();

		return (retVal);

}

MX_UINT16 FCD_ADC1_ReadAsInt()
{
	
		MX_UINT16 retVal;

		//Configure & Enable ADC Channel
		FC_CAL_Enable_ADC ( ADC_5_MX_ADC_CHANNEL , ADC_5_MX_ADC_CONVSP , ADC_5_MX_ADC_VREFOP , ADC_5_MX_ADC_ACTIME );

		retVal = FC_CAL_Sample_ADC( 1 );				//Perform Sample - Return as MX_UINT16

		FC_CAL_Disable_ADC ();

		return (retVal);

}

MX_FLOAT FCD_ADC1_ReadAsVoltage()
{
	
		MX_UINT16 iSample;
		MX_FLOAT fSample, fVoltage, fVperDiv;

		//Configure & Enable ADC Channel
		FC_CAL_Enable_ADC ( ADC_5_MX_ADC_CHANNEL , ADC_5_MX_ADC_CONVSP , ADC_5_MX_ADC_VREFOP , ADC_5_MX_ADC_ACTIME );

	  #ifdef MX_ADC_BITS_8
		iSample = FC_CAL_Sample_ADC( 0 );								//Perform Sample - Return as byte
	  #else
		iSample = FC_CAL_Sample_ADC( 1 );								//Perform Sample - Return as MX_UINT16
	  #endif

	  	FC_CAL_Disable_ADC ();											//Switch off ADC peripheral
		fVoltage = flt_fromi( ADC_5_MX_ADC_VREFVOL );						//Convert reference voltage count to floating point (0 - 500 x 10mV)
		fVoltage = flt_mul(fVoltage, 0.01);								//Convert reference voltage count to actual voltage (0 - 5)

	  #ifdef MX_ADC_BITS_8
		fVperDiv = flt_mul(fVoltage, 0.00390625);						//Convert actual voltage to voltage per division (VRef / 256)
	  #endif
	  #ifdef MX_ADC_BITS_10
		fVperDiv = flt_mul(fVoltage, 0.000976);							//Convert actual voltage to voltage per division (VRef / 1024)
	  #endif
	  #ifdef MX_ADC_BITS_12
		fVperDiv = flt_mul(fVoltage, 0.00024414);						//Convert actual voltage to voltage per division (VRef / 4096)
	  #endif

		fSample = flt_fromi(iSample);									//Convert to floating point variable
		fVoltage = flt_mul(fSample, fVperDiv);							//Calculate floating point voltage

		return (fVoltage);

}

void FCD_ADC1_ReadAsString(MX_CHAR* FCR_RETVAL, MX_UINT8 FCR_RETVAL_SIZE)
{
	
		MX_FLOAT fVoltage;

		fVoltage = FCD_ADC1_ReadAsVoltage();
		FCI_FLOAT_TO_STRING(fVoltage, 2, FCR_RETVAL, FCR_RETVAL_SIZE);	//Convert to String

}

void FCD_ADC1_ADC_RAW_Configure_Channel()
{
	
		//Configure & Enable ADC Channel
		FC_CAL_Enable_ADC ( ADC_5_MX_ADC_CHANNEL , ADC_5_MX_ADC_CONVSP , ADC_5_MX_ADC_VREFOP , ADC_5_MX_ADC_ACTIME );

}

MX_UINT8 FCD_ADC1_ADC_RAW_Sample_Channel_Byte()
{
	
		return FC_CAL_Sample_ADC( 0 );									//Perform Sample - Return as byte

}

MX_UINT16 FCD_ADC1_ADC_RAW_Sample_Channel_Int()
{
	
		return FC_CAL_Sample_ADC( 1 );									//Perform Sample - Return as MX_UINT16

}

MX_UINT8 FCD_ADC1_ADC_RAW_Average_Channel_Byte(MX_UINT8 NumSamples, MX_UINT8 DelayUs)
{
	
		MX_UINT32 average = 0;
		MX_UINT8 count;

		for (count=0; count<NumSamples; count++)
		{
			average = average + FC_CAL_Sample_ADC( 0 );					//Perform Sample - Return as byte - add to average

			if (DelayUs)
				delay_us(DelayUs);										//If delay is not 0 then pause between samples
		}
		average = average / count;

		return (average & 0xFF);										//Return average as byte

}

MX_UINT16 FCD_ADC1_ADC_RAW_Average_Channel_Int(MX_UINT8 NumSamples, MX_UINT8 DelayUs)
{
	
		MX_UINT32 average = 0;
		MX_UINT8 count;

		for (count=0; count<NumSamples; count++)
		{
			average = average + FC_CAL_Sample_ADC( 1 );					//Perform Sample - Return as MX_UINT16 - add to average

			if (DelayUs)
				delay_us(DelayUs);										//If delay is not 0 then pause between samples
		}
		average = average / count;

		return (average & 0x1FFF);										//Return average as MX_SINT16

}

void FCD_ADC1_ADC_RAW_Disable_Channel()
{
	
		FC_CAL_Disable_ADC ();											//Disable ADC Channel

}

#include "C:\Program Files (x86)\Flowcode\v5\CAL\includes.c"

//Macro implementations

//U ovom zadatku smo pomocu PWM modula i potenciometara podesavli intenzitet svijetlosti LED sa odredjenim kasnjenjem promjene od 500 ms.


void main()
{
	//Initialization
	adcon1 = 0x07;


	//Interrupt initialization code
	option_reg = 0xC0;


	//Pozivamo makro komponentu za ukljucivanje prvog PWM modula
	//Call Component Macro: Enable()
	FCD_PWM0_Enable();

	//Pozivamo makro komponentu za ukljucivanje drugog PWM modula
	//Call Component Macro: Enable()
	FCD_PWM1_Enable();

	//Definisemo varijable i njiihove pocetne vrijednosti
	//Calculation:
	//  Napon = 255
	//  Naponjedan = 0
	FCV_NAPON = 255;
	FCV_NAPONJEDAN = 0;

	//Loop
	//Loop: While 1
	while (1)
	{

		//Pozivamo makro komponentu da procita vrijednosti u Byte i zapise
		//Call Component Macro: Naponjedan=ReadAsByte()
		FCV_NAPONJEDAN = FCD_ADC1_ReadAsByte();

		//Call Component Macro
		//Call Component Macro: SetDutyCycle(Naponjedan)
		FCD_PWM1_SetDutyCycle(FCV_NAPONJEDAN);

		//Comment:
		//U prva dva bloka smo rekli da prvi potenciometar cita vrijednost napona
		//u Byte te ih zapisuje u varijablu Naponjedan. Tako je isto za drugi 
		//potenciometar gdje zapisuje u varijablu Napon. 
		//Pomocu prvog PWM modula prikazujemo sirinsku impulsno moduaciju koristenjem
		//SetDutyCycle iz varijable naponjedan. Tako je i za drugi PWM modul.

		//Call Component Macro
		//Call Component Macro: SetDutyCycle(Napon)
		FCD_PWM0_SetDutyCycle(FCV_NAPON);

		//Promjena se desava svakih 500 ms kada okrecemo potenciometar
		//Delay: 500 ms
		delay_ms(255);
		delay_ms(245);

		//Pozivamo makro komponentu da procita u Byte i zapise u varijablu
		//Call Component Macro: Napon=ReadAsByte()
		FCV_NAPON = FCD_ADC0_ReadAsByte();


	}

	mainendloop: goto mainendloop;
}

void MX_INTERRUPT_MACRO(void)
{
}



