//************************************************************************************
//**  
//**  File name:     E:\Skola\Mirkoracunari\DC motor\dc_motor.c
//**  Title:         
//**  Description:   
//**  
//**  Generated by:  Flowcode v5.5.2.1
//**  Date:          Sunday, March 25, 2018 19:01:38
//**  Licence:       Professional
//**  Registered to: xyz
//**  Licence key:   WUK7B9
//**  
//**  
//**  http://www.matrixmultimedia.com
//**  
//************************************************************************************


#define MX_PIC

#define MX_USES_UINT8 1
#define MX_USES_SINT16 0
#define MX_USES_CHAR 0
#define MX_USES_FLOAT 0
#define MX_USES_SINT32 0
#define MX_USES_BOOL 1
#define MX_USES_UINT16 0
#define MX_USES_UINT32 0
//Defines for microcontroller
#define P16F877
#define FC_CAL_PIC
#define MX_ADC
#define MX_ADC_TYPE_30
#define MX_ADC_BITS_10
#define MX_EE
#define MX_EE_TYPE2
#define MX_EE_SIZE 256
#define MX_SPI_1
#define MX_SPI_1_MISO_PORT portc
#define MX_SPI_1_MISO_TRIS trisc
#define MX_SPI_1_MISO_PIN 4
#define MX_SPI_1_MOSI_PORT portc
#define MX_SPI_1_MOSI_TRIS trisc
#define MX_SPI_1_MOSI_PIN 5
#define MX_SPI_1_CLK_PORT portc
#define MX_SPI_1_CLK_TRIS trisc
#define MX_SPI_1_CLK_PIN 3
#define MX_SPI_1_SS_PORT portc
#define MX_SPI_1_SS_TRIS trisc
#define MX_UART_1
#define MX_UART_1_TX_PORT portc
#define MX_UART_1_TX_TRIS trisc
#define MX_UART_1_TX_PIN 6
#define MX_UART_1_RX_PORT portc
#define MX_UART_1_RX_TRIS trisc
#define MX_UART_1_RX_PIN 7
#define MX_I2C
#define MX_MI2C
#define MX_I2C_1
#define MX_I2C_1_SDA_PORT portc
#define MX_I2C_1_SDA_TRIS trisc
#define MX_I2C_1_SDA_PIN 4
#define MX_I2C_1_SCL_PORT portc
#define MX_I2C_1_SCL_TRIS trisc
#define MX_I2C_1_SCL_PIN 3
#define MX_PWM
#define MX_PWM_CNT 2
#define MX_PWM_PSCA1
#define MX_PWM_PSCA4
#define MX_PWM_PSCA16
#define MX_PWM_1_PORT portc
#define MX_PWM_1_TRIS trisc
#define MX_PWM_1_PIN 2
#define MX_PWM_2_PORT portc
#define MX_PWM_2_TRIS trisc
#define MX_PWM_2_PIN 1

//Functions
#define MX_CLK_SPEED 10000000
#ifdef _BOOSTC
#include <system.h>
#endif
#ifdef HI_TECH_C
#include <pic.h>
#endif

//Configuration data
#ifdef _BOOSTC
#pragma DATA 0x2007, 0x3f7a
#endif
#ifdef HI_TECH_C
__CONFIG(0x3f7a);
#endif

//Internal functions
#include "C:\Program Files (x86)\Flowcode\v5\FCD\internals.c"

//Macro function declarations


//Variable declarations
#define FCV_TRUE (1)
#define FCV_FALSE (0)
MX_UINT8 FCV_STOP;
MX_UINT8 FCV_ENABLE;
MX_UINT8 FCV_RIGHT;
MX_UINT8 FCV_LEFT;
MX_UINT8 FCV_INPUT1;
MX_UINT8 FCV_INPUT2;



#include "C:\Program Files (x86)\Flowcode\v5\CAL\includes.c"

//Macro implementations

//U ovom zadatku cilj nam je mikroracunarom upravljati DC motorom


void main()
{
	//Initialization
	adcon1 = 0x07;


	//Interrupt initialization code
	option_reg = 0xC0;


	//Gasimo sve led na portu C
	//Output: 0 -> PORTC
	trisc = 0x00;
	portc = (0);

	//Definisemo varijable i njihove pocetne vrijednosti
	//Calculation:
	//  Enable = 0
	//  Input1 = 0
	//  Input2 = 0
	//  Left = 1
	//  Right = 1
	//  Stop = 1
	FCV_ENABLE = 0;
	FCV_INPUT1 = 0;
	FCV_INPUT2 = 0;
	FCV_LEFT = 1;
	FCV_RIGHT = 1;
	FCV_STOP = 1;

	//Loop
	//Loop: While 1
	while (1)
	{

		//Definisemo ulaz u ovom slucaju taster za vrijednost varijable ri
		//Input: A0 -> Right
		trisa = trisa | 0x01;
		FCV_RIGHT = ((porta & 0x01) == 0x01);

		//Ako je desni taster pritisnut a taster za lijevo nije 
		//Decision: (Right = 0) AND (Left = 1)?
		if ((FCV_RIGHT == 0) & (FCV_LEFT == 1))
		{

			//Definisemo varijable za okretanje motora u desno
			//Calculation:
			//  Enable = 1
			//  Input1 = 1
			//  Input2 = 0
			FCV_ENABLE = 1;
			FCV_INPUT1 = 1;
			FCV_INPUT2 = 0;

			//Enable je izlaz i nalazi se portu C bit 0
			//Output: Enable -> C0
			trisc = trisc & 0xFE;
			if ((FCV_ENABLE))
				portc = (portc & 0xFE) | 0x01;
			else
				portc = portc & 0xFE;

			//Izlaz a to je ulaz u motora nalazi na portu c bit 1
			//Output: Input1 -> C1
			trisc = trisc & 0xFD;
			if ((FCV_INPUT1))
				portc = (portc & 0xFD) | 0x02;
			else
				portc = portc & 0xFD;

			//Input2 se nalazi na portu c
			//Output: Input2 -> C2
			trisc = trisc & 0xFB;
			if ((FCV_INPUT2))
				portc = (portc & 0xFB) | 0x04;
			else
				portc = portc & 0xFB;

		// } else {

		}

		//Definisemo ulaz u ovom slucaju taster za naredbu 
		//Input: A2 -> Stop
		trisa = trisa | 0x04;
		FCV_STOP = ((porta & 0x04) == 0x04);

		//Ako je taster stop pritisnut
		//Decision: Stop = 0?
		if (FCV_STOP == 0)
		{

			//Definisemo varijable i njihove vrijednosti pocetne za stop
			//Calculation:
			//  Enable = 0
			//  Input1 = 0
			//  Input2 = 0
			FCV_ENABLE = 0;
			FCV_INPUT1 = 0;
			FCV_INPUT2 = 0;

			//Gasimo sve led na portu C, odnosno stopiratmo kretanje Dc motora
			//Output: 0 -> PORTC
			trisc = 0x00;
			portc = (0);

		// } else {

		}

		//Definisemo ulaz u ovom slucaju taster za vrijednost varijable lf
		//Input: A1 -> Left
		trisa = trisa | 0x02;
		FCV_LEFT = ((porta & 0x02) == 0x02);

		//Ako je taster left pritisnut, a taster rigth nije pritisnut 
		//Decision: (Left = 0) AND (Right = 1)?
		if ((FCV_LEFT == 0) & (FCV_RIGHT == 1))
		{

			//Definisemo vrijednost varijable i njihove poctene vrijednosti 
			//Calculation:
			//  Enable = 1
			//  Input1 = 0
			//  Input2 = 1
			FCV_ENABLE = 1;
			FCV_INPUT1 = 0;
			FCV_INPUT2 = 1;

			//Izlaz se nalazi na portu C bit 0
			//Output: Enable -> C0
			trisc = trisc & 0xFE;
			if ((FCV_ENABLE))
				portc = (portc & 0xFE) | 0x01;
			else
				portc = portc & 0xFE;

			//Definisemo izlaz na portu C koji je ulaz u DC motor
			//Output: Input1 -> C1
			trisc = trisc & 0xFD;
			if ((FCV_INPUT1))
				portc = (portc & 0xFD) | 0x02;
			else
				portc = portc & 0xFD;

			//Definisemo izlaz na portu C bit 2 koji je ujendo ulaz za DC moto
			//Output: Input2 -> C2
			trisc = trisc & 0xFB;
			if ((FCV_INPUT2))
				portc = (portc & 0xFB) | 0x04;
			else
				portc = portc & 0xFB;

		// } else {

		}


	}

	mainendloop: goto mainendloop;
}

void MX_INTERRUPT_MACRO(void)
{
}



