//************************************************************************************
//**  
//**  File name:     D:\Skola\Mirkoracunari\DC motor sa PWM\dc_pwm.c
//**  Title:         
//**  Description:   
//**  
//**  Generated by:  Flowcode v5.5.2.1
//**  Date:          Sunday, April 01, 2018 12:29:48
//**  Licence:       Professional
//**  Registered to: xyz
//**  Licence key:   WUK7B9
//**  
//**  
//**  http://www.matrixmultimedia.com
//**  
//************************************************************************************


#define MX_PIC

#define MX_USES_UINT8 1
#define MX_USES_SINT16 0
#define MX_USES_CHAR 0
#define MX_USES_FLOAT 0
#define MX_USES_SINT32 0
#define MX_USES_BOOL 1
#define MX_USES_UINT16 0
#define MX_USES_UINT32 0
//Defines for microcontroller
#define P16F877
#define FC_CAL_PIC
#define MX_ADC
#define MX_ADC_TYPE_30
#define MX_ADC_BITS_10
#define MX_EE
#define MX_EE_TYPE2
#define MX_EE_SIZE 256
#define MX_SPI_1
#define MX_SPI_1_MISO_PORT portc
#define MX_SPI_1_MISO_TRIS trisc
#define MX_SPI_1_MISO_PIN 4
#define MX_SPI_1_MOSI_PORT portc
#define MX_SPI_1_MOSI_TRIS trisc
#define MX_SPI_1_MOSI_PIN 5
#define MX_SPI_1_CLK_PORT portc
#define MX_SPI_1_CLK_TRIS trisc
#define MX_SPI_1_CLK_PIN 3
#define MX_SPI_1_SS_PORT portc
#define MX_SPI_1_SS_TRIS trisc
#define MX_UART_1
#define MX_UART_1_TX_PORT portc
#define MX_UART_1_TX_TRIS trisc
#define MX_UART_1_TX_PIN 6
#define MX_UART_1_RX_PORT portc
#define MX_UART_1_RX_TRIS trisc
#define MX_UART_1_RX_PIN 7
#define MX_I2C
#define MX_MI2C
#define MX_I2C_1
#define MX_I2C_1_SDA_PORT portc
#define MX_I2C_1_SDA_TRIS trisc
#define MX_I2C_1_SDA_PIN 4
#define MX_I2C_1_SCL_PORT portc
#define MX_I2C_1_SCL_TRIS trisc
#define MX_I2C_1_SCL_PIN 3
#define MX_PWM
#define MX_PWM_CNT 2
#define MX_PWM_PSCA1
#define MX_PWM_PSCA4
#define MX_PWM_PSCA16
#define MX_PWM_1_PORT portc
#define MX_PWM_1_TRIS trisc
#define MX_PWM_1_PIN 2
#define MX_PWM_2_PORT portc
#define MX_PWM_2_TRIS trisc
#define MX_PWM_2_PIN 1

//Functions
#define MX_CLK_SPEED 10000000
#ifdef _BOOSTC
#include <system.h>
#endif
#ifdef HI_TECH_C
#include <pic.h>
#endif

//Configuration data
#ifdef _BOOSTC
#pragma DATA 0x2007, 0x3f7a
#endif
#ifdef HI_TECH_C
__CONFIG(0x3f7a);
#endif

//Internal functions
#include "C:\Program Files (x86)\Flowcode\v5\FCD\internals.c"

//Macro function declarations


//Variable declarations
#define FCV_TRUE (1)
#define FCV_FALSE (0)
MX_UINT8 FCV_BRZINA;




//PWM(0): //Defines:

/**** Macro Substitutions ****
a = Unique Reference
b = PWM Channel - 0=SW / 1-8=HW
c = PWM Alt Pin FCD_PWM0_Enable - 0=Standard / 1=Alt
d = PWM Period
e = PWM Prescaler 1
******************************/

//Period and Prescaler Defines
#ifndef MX_PWM_PERIOD
  #define MX_PWM_PERIOD				255
#else
  #if (MX_PWM_PERIOD != 255)
    #error "PWM period value must be the same in all PWM modules"
  #endif
#endif

#ifndef MX_PWM_PRESCALE1
  #define MX_PWM_PRESCALE1			1
#else
  #if (MX_PWM_PRESCALE1 != 1)
    #error "PWM prescale value must be the same in all PWM modules"
  #endif
#endif

//Definitions for PWM slot allocation
#ifndef	MX_PWM_REF1
				#define MX_PWM_REF1
				#define PWM_1_MX_PWM_UREF			1
				#define MX_PWM_CHANNEL_1		1
				#define MX_PWM_HWALT_1			0
#else
 #ifndef	MX_PWM_REF2
				#define MX_PWM_REF2
				#define PWM_1_MX_PWM_UREF			2
				#define MX_PWM_CHANNEL_2		1
				#define MX_PWM_HWALT_2			0
 #else
  #ifndef	MX_PWM_REF3
				#define MX_PWM_REF3
				#define PWM_1_MX_PWM_UREF			3
				#define MX_PWM_CHANNEL_3		1
				#define MX_PWM_HWALT_3			0
  #else
   #ifndef	MX_PWM_REF4
				#define MX_PWM_REF4
				#define PWM_1_MX_PWM_UREF			4
				#define MX_PWM_CHANNEL_4		1
				#define MX_PWM_HWALT_4			0
   #else
    #ifndef	MX_PWM_REF5
				#define MX_PWM_REF5
				#define PWM_1_MX_PWM_UREF			5
				#define MX_PWM_CHANNEL_5		1
				#define MX_PWM_HWALT_5			0
    #else
     #ifndef	MX_PWM_REF6
				#define MX_PWM_REF6
				#define PWM_1_MX_PWM_UREF			6
				#define MX_PWM_CHANNEL_6		1
				#define MX_PWM_HWALT_6			0
     #else
      #ifndef	MX_PWM_REF7
				#define MX_PWM_REF7
				#define PWM_1_MX_PWM_UREF			7
				#define MX_PWM_CHANNEL_7		1
				#define MX_PWM_HWALT_7			0
      #else
       #ifndef	MX_PWM_REF8
				#define MX_PWM_REF8
				#define PWM_1_MX_PWM_UREF			8
				#define MX_PWM_CHANNEL_8		1
				#define MX_PWM_HWALT_8			0
       #else
        #ifndef	MX_PWM_REF9
				#define MX_PWM_REF9
				#define PWM_1_MX_PWM_UREF			9
				#define MX_PWM_CHANNEL_9		1
				#define MX_PWM_HWALT_9			0
        #else
         #ifndef	MX_PWM_REF10
				#define MX_PWM_REF10
				#define PWM_1_MX_PWM_UREF			10
				#define MX_PWM_CHANNEL_10		1
				#define MX_PWM_HWALT_10			0
         #else
          #ifndef	MX_PWM_REF11
				#define MX_PWM_REF11
				#define PWM_1_MX_PWM_UREF			11
				#define MX_PWM_CHANNEL_11		1
				#define MX_PWM_HWALT_11			0
          #else
           #ifndef	MX_PWM_REF12
				#define MX_PWM_REF12
				#define PWM_1_MX_PWM_UREF			12
				#define MX_PWM_CHANNEL_12		1
				#define MX_PWM_HWALT_12			0
           #else
            #ifndef	MX_PWM_REF13
				#define MX_PWM_REF13
				#define PWM_1_MX_PWM_UREF			13
				#define MX_PWM_CHANNEL_13		1
				#define MX_PWM_HWALT_13			0
            #else
             #ifndef	MX_PWM_REF14
				#define MX_PWM_REF14
				#define PWM_1_MX_PWM_UREF			14
				#define MX_PWM_CHANNEL_14		1
				#define MX_PWM_HWALT_14			0
             #else
         	  #ifndef	MX_PWM_REF15
				#define MX_PWM_REF15
				#define PWM_1_MX_PWM_UREF			15
				#define MX_PWM_CHANNEL_15		1
				#define MX_PWM_HWALT_15			0
              #else
               #ifndef	MX_PWM_REF16
				#define MX_PWM_REF16
				#define PWM_1_MX_PWM_UREF			16
				#define MX_PWM_CHANNEL_16		1
				#define MX_PWM_HWALT_16			0
			   #endif
			  #endif
			 #endif
			#endif
		   #endif
		  #endif
         #endif
        #endif
       #endif
      #endif
     #endif
    #endif
   #endif
  #endif
 #endif
#endif

#define PWM_1_PWM_Enable_Channel		CAL_APPEND(FC_CAL_PWM_Enable_Channel_, PWM_1_MX_PWM_UREF)
#define PWM_1_PWM_Disable_Channel		CAL_APPEND(FC_CAL_PWM_Disable_Channel_, PWM_1_MX_PWM_UREF)
#define PWM_1_PWM_Set_Duty_8Bit		CAL_APPEND(FC_CAL_PWM_Set_Duty_8Bit_, PWM_1_MX_PWM_UREF)
#define PWM_1_PWM_Change_Period		CAL_APPEND(FC_CAL_PWM_Change_Period_, PWM_1_MX_PWM_UREF)
#define PWM_1_PWM_Set_Duty_10Bit		CAL_APPEND(FC_CAL_PWM_Set_Duty_10Bit_, PWM_1_MX_PWM_UREF)

extern void PWM_1_PWM_Enable_Channel ();
extern void PWM_1_PWM_Disable_Channel ();
extern void PWM_1_PWM_Set_Duty_8Bit (MX_UINT8 duty);
extern void PWM_1_PWM_Change_Period (MX_UINT8 period, MX_UINT16 prescaler);
extern void PWM_1_PWM_Set_Duty_10Bit (MX_UINT16 duty);




//PWM(0): //Macro function declarations

void FCD_PWM0_Enable();
void FCD_PWM0_Disable();
void FCD_PWM0_SetDutyCycle(MX_UINT8 nDuty);
void FCD_PWM0_ChangePeriod(MX_UINT8 nPeriodVal, MX_UINT8 nPrescalerVal);
void FCD_PWM0_SetDutyCycle10bit(MX_SINT16 nDuty);



//PWM(0): //Macro implementations


void FCD_PWM0_Enable()
{
	
		PWM_1_PWM_Change_Period (MX_PWM_PERIOD, MX_PWM_PRESCALE1);
		PWM_1_PWM_Enable_Channel ();

}

void FCD_PWM0_Disable()
{
	
		PWM_1_PWM_Disable_Channel();

}

void FCD_PWM0_SetDutyCycle(MX_UINT8 nDuty)
{
	
		PWM_1_PWM_Set_Duty_8Bit(nDuty);

}

void FCD_PWM0_ChangePeriod(MX_UINT8 nPeriodVal, MX_UINT8 nPrescalerVal)
{
	
		PWM_1_PWM_Change_Period (nPeriodVal, nPrescalerVal);

}

void FCD_PWM0_SetDutyCycle10bit(MX_SINT16 nDuty)
{
	
		PWM_1_PWM_Set_Duty_10Bit(nDuty);

}

#include "C:\Program Files (x86)\Flowcode\v5\CAL\includes.c"

//Macro implementations

//U ovom zadatku smo pomoc PWM-a automatski povecali brzinu motora svakih 500 ms.


void main()
{
	//Initialization
	adcon1 = 0x07;


	//Interrupt initialization code
	option_reg = 0xC0;


	//Definisemo varijable i njihove pocetne vrijednosti
	//Calculation:
	//  Brzina = 0
	FCV_BRZINA = 0;

	//Pozivamo makrokomponentu da pwm bude dostupan
	//Call Component Macro: Enable()
	FCD_PWM0_Enable();

	//Loop
	//Loop: While 1
	while (1)
	{

		//Saljevo vrijednost logicke 1 na port c bit 0 tj. na enable motor
		//Output: 1 -> C0
		trisc = trisc & 0xFE;
		if ((1))
			portc = (portc & 0xFE) | 0x01;
		else
			portc = portc & 0xFE;

		//Saljemo vrijednost log. 0 na port c bit tj. na input 1 motora dc
		//Output: 0 -> C1
		trisc = trisc & 0xFD;
		if ((0))
			portc = (portc & 0xFD) | 0x02;
		else
			portc = portc & 0xFD;

		//Saljemo vrijednost log. 1 na port c bit 2 tj. na input 2 dc mot.
		//Output: 1 -> C2
		trisc = trisc & 0xFB;
		if ((1))
			portc = (portc & 0xFB) | 0x04;
		else
			portc = portc & 0xFB;

		//Ako je brzina manja od 250 u sledecem bloku brzina ce se povecat
		//Loop: While Brzina < 250
		while (FCV_BRZINA < 250)
		{

			//Pozivamo makrokomponentu pwm-a da prikazemo sirinsko impulsnu...
			//Call Component Macro: SetDutyCycle(Brzina)
			FCD_PWM0_SetDutyCycle(FCV_BRZINA);

			//Definismeo vriendost varijable da se brzina povecava za 5 
			//Calculation:
			//  Brzina = Brzina + 5
			FCV_BRZINA = FCV_BRZINA + 5;

			//Vrijeme za koje ce se brzina povecavati
			//Delay: 500 ms
			delay_ms(255);
			delay_ms(245);


		}

		//Definismoe vrijednost varijable i njezinu vrijednost da u ovom..
		//Calculation:
		//  Brzina = 0
		FCV_BRZINA = 0;


	}

	mainendloop: goto mainendloop;
}

void MX_INTERRUPT_MACRO(void)
{
}



