//************************************************************************************
//**  
//**  File name:     D:\Skola\Mirkoracunari\DC motor sa automatski lijevo i desno\dc_automatski_lijevo_desno.c
//**  Title:         
//**  Description:   
//**  
//**  Generated by:  Flowcode v5.5.2.1
//**  Date:          Sunday, April 01, 2018 12:05:02
//**  Licence:       Professional
//**  Registered to: xyz
//**  Licence key:   WUK7B9
//**  
//**  
//**  http://www.matrixmultimedia.com
//**  
//************************************************************************************


#define MX_PIC

#define MX_USES_UINT8 1
#define MX_USES_SINT16 0
#define MX_USES_CHAR 0
#define MX_USES_FLOAT 0
#define MX_USES_SINT32 0
#define MX_USES_BOOL 1
#define MX_USES_UINT16 0
#define MX_USES_UINT32 0
//Defines for microcontroller
#define P16F877
#define FC_CAL_PIC
#define MX_ADC
#define MX_ADC_TYPE_30
#define MX_ADC_BITS_10
#define MX_EE
#define MX_EE_TYPE2
#define MX_EE_SIZE 256
#define MX_SPI_1
#define MX_SPI_1_MISO_PORT portc
#define MX_SPI_1_MISO_TRIS trisc
#define MX_SPI_1_MISO_PIN 4
#define MX_SPI_1_MOSI_PORT portc
#define MX_SPI_1_MOSI_TRIS trisc
#define MX_SPI_1_MOSI_PIN 5
#define MX_SPI_1_CLK_PORT portc
#define MX_SPI_1_CLK_TRIS trisc
#define MX_SPI_1_CLK_PIN 3
#define MX_SPI_1_SS_PORT portc
#define MX_SPI_1_SS_TRIS trisc
#define MX_UART_1
#define MX_UART_1_TX_PORT portc
#define MX_UART_1_TX_TRIS trisc
#define MX_UART_1_TX_PIN 6
#define MX_UART_1_RX_PORT portc
#define MX_UART_1_RX_TRIS trisc
#define MX_UART_1_RX_PIN 7
#define MX_I2C
#define MX_MI2C
#define MX_I2C_1
#define MX_I2C_1_SDA_PORT portc
#define MX_I2C_1_SDA_TRIS trisc
#define MX_I2C_1_SDA_PIN 4
#define MX_I2C_1_SCL_PORT portc
#define MX_I2C_1_SCL_TRIS trisc
#define MX_I2C_1_SCL_PIN 3
#define MX_PWM
#define MX_PWM_CNT 2
#define MX_PWM_PSCA1
#define MX_PWM_PSCA4
#define MX_PWM_PSCA16
#define MX_PWM_1_PORT portc
#define MX_PWM_1_TRIS trisc
#define MX_PWM_1_PIN 2
#define MX_PWM_2_PORT portc
#define MX_PWM_2_TRIS trisc
#define MX_PWM_2_PIN 1

//Functions
#define MX_CLK_SPEED 10000000
#ifdef _BOOSTC
#include <system.h>
#endif
#ifdef HI_TECH_C
#include <pic.h>
#endif

//Configuration data
#ifdef _BOOSTC
#pragma DATA 0x2007, 0x3f7a
#endif
#ifdef HI_TECH_C
__CONFIG(0x3f7a);
#endif

//Internal functions
#include "C:\Program Files (x86)\Flowcode\v5\FCD\internals.c"

//Macro function declarations


//Variable declarations
#define FCV_FALSE (0)
#define FCV_TRUE (1)
MX_UINT8 FCV_ENABLE;
MX_UINT8 FCV_INPUT1;
MX_UINT8 FCV_INPUT2;



#include "C:\Program Files (x86)\Flowcode\v5\CAL\includes.c"

//Macro implementations

//U zadataku upravljali DC motorom pomocu digitalnih izlaza. To jeste da se motor okrece 5 sekundi u desnu i  zatim u lijevu stranu.


void main()
{
	//Initialization
	adcon1 = 0x07;


	//Interrupt initialization code
	option_reg = 0xC0;


	//Loop
	//Loop: While 1
	while (1)
	{

		//Saljemo logicku 1 na enable port c bit 0
		//Output: 1 -> C0
		trisc = trisc & 0xFE;
		if ((1))
			portc = (portc & 0xFE) | 0x01;
		else
			portc = portc & 0xFE;

		//Saljemo vrijednost 1 na port c bit 1 
		//Output: 1 -> C1
		trisc = trisc & 0xFD;
		if ((1))
			portc = (portc & 0xFD) | 0x02;
		else
			portc = portc & 0xFD;

		//I saljemo vrijednost logiccke 0 na port c bit 2
		//Output: 0 -> C2
		trisc = trisc & 0xFB;
		if ((0))
			portc = (portc & 0xFB) | 0x04;
		else
			portc = portc & 0xFB;

		//Vrijeme za koje ce motoro okretati u desno
		//Delay: 5 s
		delay_s(5);

		//Saljemo vrijednost logicke 0 na port c bit 0
		//Output: 0 -> C0
		trisc = trisc & 0xFE;
		if ((0))
			portc = (portc & 0xFE) | 0x01;
		else
			portc = portc & 0xFE;

		//Vrijeme za koje ce se motor prestati okretati
		//Delay: 3 s
		delay_s(3);

		//Saljemo vrijednost logicke 1 na port c bit 0 tj. na enable
		//Output: 1 -> C0
		trisc = trisc & 0xFE;
		if ((1))
			portc = (portc & 0xFE) | 0x01;
		else
			portc = portc & 0xFE;

		//Saljemo vrijednost 0 na port c bit 1 tj. input 1
		//Output: 0 -> C1
		trisc = trisc & 0xFD;
		if ((0))
			portc = (portc & 0xFD) | 0x02;
		else
			portc = portc & 0xFD;

		//Saljemo vrijendost logicke 1 na port c bit 2 tj.input 2
		//Output: 1 -> C2
		trisc = trisc & 0xFB;
		if ((1))
			portc = (portc & 0xFB) | 0x04;
		else
			portc = portc & 0xFB;

		//Vrijeme za koje ce se okretati motor u desno
		//Delay: 5 s
		delay_s(5);

		//Motor ce se iskljuciti jer saljemo log. 0 na port c bit 0
		//Output: 0 -> C0
		trisc = trisc & 0xFE;
		if ((0))
			portc = (portc & 0xFE) | 0x01;
		else
			portc = portc & 0xFE;

		//Vrijme za koje ce motor biti iskljucen
		//Delay: 3 s
		delay_s(3);


	}

	mainendloop: goto mainendloop;
}

void MX_INTERRUPT_MACRO(void)
{
}



